### ISSUE TITLE
Deploy Diego

### ISSUE THREAD

**Issue by ghost** [18F/cg-atlas#102]
In order to make Diego available to platform users, as ops engineers we need to deploy Diego integrated with the existing CF deployment.
#### Acceptance Criteria
- [x] A concourse pipeline task that pulls in the dynamically generated CF manifest and feeds it to the Diego manifest generation script
- [ ] A concourse pipeline that deploys an appropriate version of Diego for the deployed version of CF
- [ ] A concourse pipeline task that runs the smoke tests to exercise diego
- [ ] A concourse pipeline task that runs the acceptance tests to exercise diego

**Comment by mogul** [comment]
Mike's going to start pushing up branches so that other people can see work-in-progress via a PR

**Comment by ghost** [comment]
WIP pushed to https://github.com/18F/cg-deploy-diego

**Comment by mogul** [comment]
Per standup today, Terraform scripts done, should be able to test the deployment soon.

**Comment by frsfx** [comment]
All AWS resources were provisioned in Staging for Diego using cg-provision pipeline.

**Comment by frsfx** [comment]
In order to approve Diego for production and ready for use in GovCloud the following criteria must be met:
- [ ]  Deployed
- [ ]  Run automated tests from upstream
- [ ]  Deploy cloud.gov apps with monitoring
- [ ]  Migrate some 18F apps
- [ ]  Migrate sandboxes
- [ ]  Migrate more risky stuff
- [ ]  Migrate Dept of ED, college scorecard

**Comment by ghost** [comment]
Duplicate of https://github.com/18F/cg-product/issues/22
