### ISSUE TITLE
Concourse deployment of the aws-rds broker

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#43]
We have multiple brokers which are not yet in a CI pipeline.  In order to progress towards our goal of automated, repeatable deployments we should create a Concourse pipeline to deliver the service
- [x] Create reusable broker pipeline in Concourse - https://github.com/18F/aws-broker/pull/7
- [x] aws-rds broker is deployed by pipeline
- [x] aws-rds required database is deployed via Terraform for net-new broker instances
- [x] aws-rds deployments not restricted to us-east-1 - https://github.com/18F/aws-broker/pull/11

**Comment by sharms** [comment]
We have created a minimum viable terraform RDS profile along with IAM permissions, and are looking to be able to deploy to staging by close of business today

**Comment by jmcarp** [comment]
Update: as of http://ci.cloud.gov/pipelines/deploy-aws-broker-staging/jobs/push-aws-broker/builds/21, we're provisioning databases and deploying to staging. We should be able to pull in something like https://github.com/18F/aws-broker/compare/master...jmcarp:update-broker?expand=1, and then we'll have the broker registering itself and updating its catalog on deploy.

From there, it sounds like we'll want to run some kind of acceptance tests on staging before deploying to production, which I'm guessing will be something along the lines of creating a service instance, binding it to an app, and verifying that the expect credentials are injected into the app environment.

**Comment by mogul** [comment]
Are there any data migration concerns for the hand-propped broker that's out there in AWS E/W prod environment now?

**Comment by jmcarp** [comment]
There aren't any schema changes pending, so all we need to do is point what we're calling `rds-internal` to the existing rds instance, or create the new rds instance from a backup of the existing instance. I'm hoping we can point our terraform rds module to the instance id of the existing database, which would require exposing that attribute in our module, unless there's a better approach--@LinuxBozo, what do you think?

This reminds me of a few related issues:
- There are currently two brokers that support rds: `aws-broker` and `rds-broker`. Is the idea to retire `rds-broker` in favor of `aws-broker`?
- The current deploy of `aws-broker` uses a mysql rds instance to store internal state and for the `shared-msql` plan, and a postgres rds instance for the `shared-psql` plan. This PR uses three instances: one for internal state (can be postgres or mysql), one for `shared-mysql`, and one for `shared-postgres`. I think this is better than keeping internal state and shared data in the same place, but it makes the migration a little more complicated, since we're mapping three rds instances to two. Maybe copying the current internal rds instance from a backup is the way to go here.

**Comment by mogul** [comment]
> There are currently two brokers that support rds: aws-broker and rds-broker. Is the idea to retire rds-broker in favor of aws-broker?

Yes, however we must first ensure that no one's using `rds-broker` service instances before we retire it.

As a product person I have no opinions on whether the internal broker state should be split into another DB instance, nor any requirements for that before accepting, but other people on the team might have thoughts.

**Comment by LinuxBozo** [comment]
@jmcarp From my research, there is a hacky method for getting terraform to recognize already deployed bits, but it involves hacking up a proper tfstate file so that everything matches. There is this: https://github.com/dtan4/terraforming that will try to do the tfstate thing for you, but I haven't had a chance to try it.

It is a frequently requested issue though: https://github.com/hashicorp/terraform/issues/581

**Comment by jmcarp** [comment]
Update: based on conversation with @dlapiduz, we're not going to deal with migration in this issue, so we can defer the terraform question for now.

In case this comes up again later, I took a look at terraforming and was able to get terraform to manage an existing rds instance--although I had to change the generated terraform state file to get it to work with our terraform rds module.

**Comment by afeld** [comment]
I believe this is done besides deploying to GovCloud, right? If so, let's close in favor of https://github.com/18F/cg-atlas/issues/25#issuecomment-224368518.

**Comment by afeld** [comment]
Would someone mind updating the checkboxes at the top?

**Comment by mogul** [comment]
pinging

> Would someone mind updating the checkboxes at the top?

Can we close this now?

**Comment by mogul** [comment]
Closing as I'm pretty sure there's nothing left to do here.
