### ISSUE TITLE
Enabler: Upgrade UAA to 3.2.1+

### ISSUE THREAD

**Issue by mogul** [18F/cg-atlas#6]
In order to fix vulnerabilities, enable theming, support SAML clients, and increase bus-factor on our UAA deployment, we want to upgrade our production version of UAA to 3.2.1 or higher.

Acceptance Criteria:
- [ ] Production UAA is demonstrated to be running UAA 3.2.1 or higher

Notes:
- There's a (hard-to-exploit) CVE we need to fix
- Newer versions enable theming without any code modification, which we want
- We can use the new SAML IDP functionality to authenticate our ideas portal, among other things
- Having Chris run through this will help him get to grips with UAA, BOSH, and Concourse

**Comment by cnelson** [comment]
Looking at the upstream commit log: https://github.com/cloudfoundry/uaa/commits/master

It looks like 3.3.0 is going to drop real soon, just FYI depending on timing with this, we might want to go right to that version.

**Comment by cnelson** [comment]
As far as I'm concerned, the upgraded UAA in staging is now ready to go to production, but since it was left on an older version for so long, there's a risk it may cause problems that the staging tests didn't uncover.

Perhaps it's best to hold this release until after your IRL event in case triage is required after it's deployed?

**Comment by mogul** [comment]
Let's live dangerously on this one... The IRL event also means that there's
going to be a lot fewer people trying to use it for the next couple days. :)

**Comment by mogul** [comment]
This was actually updated, right? Can't remember or figure out where to look in CI to confirm, but closing on the assumption that it was, since it's awaiting acceptance. (Reopen if it's not the case.)

**Comment by cnelson** [comment]
Yeah it was.  You can view the source of the login page to see the version and commit that's running.

--
cnelson

On May 14, 2016, at 19:00, Bret Mogilefsky <notifications@github.com<mailto:notifications@github.com>> wrote:


This was actually updated, right? Can't remember or figure out where to look in CI to confirm, but closing on the assumption that it was, since it's awaiting acceptance. (Reopen if it's not the case.)

-

**Comment by cnelson** [comment]
Yeah it was.  You can view the source of the login page to see the version and commit that's running

```
$ curl https://login.cloud.gov/login | grep title
<div class="copyright" title="Version: 3.3.0, Commit: 127ab6f, Timestamp: 2016-04-27T19:50:09+0000, UAA: https://uaa.cloud.gov">
```
